### ISSUE TITLE
Published package missing lib directory

### ISSUE THREAD

**Issue by o5zhang** [Mastercard/connect-react-native-sdk#3]
Hi!

I followed the instructions to install the package (npm install connect-react-native-sdk) but when I actually try to import `Connect`, I'm getting cannot find module errors. 

According to the package.json, it seems that the main module paths point to locations within the `lib` directory:
```
"main": "lib/commonjs/index",
"module": "lib/module/index",
"types": "lib/typescript/src/index.d.ts",
```
But the `lib` directory is not present after the installation, leading to unresolved imports when I try to use `Connect`.

Wondering if you could provide guidance on how to resolve this issue. I'm not sure if there's a build step I'm missing or maybe something slipped through the package publication process?

Many thanks!

**Comment by o5zhang** [comment]
Hi @E130652gkolusu,

I can confirm that I am getting the same "cannot find module" type error, and when I run the application, it does not throw an error and works as expected (same behaviour as v1.0.0-rc.5). 

Though with the type error, our repo's CI tests aren't going to let me merge anything in. Thanks for the reply and please keep me updated.

**Comment by E130652gkolusu** [comment]
Thank you for your patience, @o5zhang.

We are currently developing a permanent solution to this issue. However, in the meantime, I'd like to propose a temporary workaround to prevent this from hindering your progress. Please consider adding the line `//@ts-ignore` above the line that's causing the error. This will instruct the CI to overlook it until we roll out a definitive fix.

![image](https://github.com/Mastercard/connect-react-native-sdk/assets/157385417/9dd2aca7-f7eb-4e79-a503-44388421d846)

**Comment by o5zhang** [comment]
Hi @E130652gkolusu,

Thanks for the reply. I added the line `//@ts-ignore` to all my imports from the connect-react-native-sdk, and while that will quiet my VS Code error messages, the CI is still throwing the type error: Cannot find module 'connect-react-native-sdk'.

For now, I'm not really blocked as v1.0.0-rc.5 is still working fine, I just wanted to bump the package since the interface has changed a bit.

Please let me know when the definitive fix has been rolled out. Thank you!

**Comment by E130652gkolusu** [comment]
Hi @o5zhang 

New version 2.0.1 is released and issue is addressed.

https://www.npmjs.com/package/connect-react-native-sdk/v/2.0.1
